{{- $name := coalesce .Values.configMap.name .Values.serviceProperties.name -}}
{{- $namespace := coalesce .Values.configMap.namespace .Values.serviceProperties.namespace -}}
{{- $enabled := .Values.configMap.enabled -}}

{{ if $enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
data:
    {{- range $k, $v := .Values.configMap.data }}
  {{ $k }}: {{ $v | quote }}
    {{- end }}
{{- end }}